#!/bin/bash

#### 
#  regenerate keymap visualizations using keymap-drawer.
#
#  
set -e

keymap_yaml="./keymap-drawer/possum_3x5_2.yaml"

# Generate layer-only svgs
keymap draw -s Base -- $keymap_yaml >assets/base_layer.svg
keymap draw -s Nav -- $keymap_yaml >assets/nav_layer.svg

# Regenerate the full alpha layout
keymap draw -- $keymap_yaml >assets/layers-only.svg
# keymap draw -s Base Nav Num Sym Macro Func System -- $keymap_yaml >assets/layers-only.svg

# # Regenerate the combos
# # Commented 4/13/23 --current keymap-drawer release is behind main and does not have slide formatting
# keymap draw -s Combos-Adjacent Combos-Vertical Combos-Other -- $keymap_yaml >assets/combos-only.svg
# echo images updated successfully.
