#!/bin/bash

#### 
#  regenerate keymap visualizations using keymap-drawer.
#
#  
set -e

keymap_yaml="./keymap-drawer/possum_3x5_2.yaml"

# Regenerate the full alpha layout
keymap draw -- $keymap_yaml >assets/possum_3x5_2.svg

# Generate layer-only svgs
keymap draw -s base -- $keymap_yaml >assets/base_layer.svg
keymap draw -s nav -- $keymap_yaml >assets/nav_layer.svg
keymap draw -s num -- $keymap_yaml >assets/num_layer.svg
keymap draw -s sym -- $keymap_yaml >assets/sym_layer.svg
keymap draw -s func -- $keymap_yaml >assets/func_layer.svg
keymap draw -s macro -- $keymap_yaml >assets/macro_layer.svg
keymap draw -s system -- $keymap_yaml >assets/system_layer.svg
